server:
  port: 7001

#eureka注册中心配置
eureka:
  #eureka服务端的实例名称
  instance.hostname: eureka
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 自我保护
    enable-self-preservation: false
    # 扫描失效服务间隔
    eviction-interval-timer-in-ms: 3000
