server:
  port: 8002

spring:
  application:
    name: user-service #服务名
#连接注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true  #支持域名直接解析ip
